version: '3.4'
services:

  fcp-sfd-frontend:
    build: 
      context: .
      target: development
    ports:
      - '3002:3002'
    environment:
      PORT: 3002
      NODE_ENV: development
    networks:
      - fcp-sfd
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json

networks:
  fcp-sfd:
    driver: bridge
