version: '3.4'
services:

  your-frontend:
    build: ./
    ports:
      - '3002:3002'
    environment:
      PORT: 3002
      NODE_ENV: development
    networks:
      - fcp-sfd

networks:
  fcp-sfd:
    driver: bridge
