services:
  fcp-sfd-frontend:
    build:
      target: development
    image: fcp-sfd-frontend-development
    container_name: fcp-sfd-frontend-test
    command: npm run test
    env_file:
      - path: .env
        required: false
    environment:
      ALLOW_ERROR_VIEWS: false
      DAL_ENDPOINT: http://fcp-dal-api:3005/graphql
      DAL_CONNECTION: true
      DEFRA_ID_WELL_KNOWN_URL: https://oidc.example.com/.well-known/openid-configuration
      DEFRA_ID_CLIENT_ID: test-client-id
      DEFRA_ID_CLIENT_SECRET: test-client-secret
      DEFRA_ID_SERVICE_ID: test-service-id
      DEFRA_ID_POLICY: test-policy
    depends_on:
      fcp-dal-api:
        condition: service_started
      kits-mock:
        condition: service_started
    volumes:
      - ./src/:/home/node/src
      - ./test/:/home/node/test
      - ./package.json:/home/node/package.json
      - ./coverage:/home/node/coverage
    networks:
      - fcp-sfd

networks:
  fcp-sfd:
    driver: bridge