export const FULL_PERMISSION = 'BUSINESS_DETAILS:FULL_PERMISSION'
export const AMEND_LEVEL_PERMISSION = 'BUSINESS_DETAILS:AMEND'
export const VIEW_LEVEL_PERMISSION = 'BUSINESS_DETAILS:VIEW'
export const MAKE_LEGAL_CHANGES_PERMISSION = 'BUSINESS_DETAILS:MAKE_LEGAL_CHANGES'

export const SCOPE = [VIEW_LEVEL_PERMISSION, AMEND_LEVEL_PERMISSION, MAKE_LEGAL_CHANGES_PERMISSION, FULL_PERMISSION]

export const VIEW_PERMISSIONS = [VIEW_LEVEL_PERMISSION, AMEND_LEVEL_PERMISSION, MAKE_LEGAL_CHANGES_PERMISSION, FULL_PERMISSION]
export const AMEND_PERMISSIONS = [AMEND_LEVEL_PERMISSION, MAKE_LEGAL_CHANGES_PERMISSION, FULL_PERMISSION]
export const LEGAL_PERMISSIONS = [MAKE_LEGAL_CHANGES_PERMISSION, FULL_PERMISSION]
export const FULL_PERMISSIONS = [FULL_PERMISSION]
